### ISSUE TITLE
How to run your code?

### ISSUE THREAD

**Issue by Mrils** [appinho/ROS_Perception_Package_Kitti_Dataset#1]
As title.

**Comment by appinho** [comment]
Hey. I can try to get a work through done within the next days. Are you still interested @Mrils  or have you already figured out how to run my code?

**Comment by Mrils** [comment]
yeah, I've compiled and run your work @appinho .But there are also some questions when i test on 0059 kitti dataset. I find that car have multiple boxes when i try to track it. That may mean there are something wrong with matching obj with tracker. Do you have find it and figure out it? Thank s for you response.

**Comment by appinho** [comment]
Currently, I am traveling with a low-performance laptop, but I will try to
compile this sequence and get further insides.

However to give you an answer now: I remember this flaw and this is
definitely due to my code. It needs further improvements to cluster the
measurements better into cars. In other words, my DBSCAN solution within
the Objection Detection is suboptimal. You can tweak some parameters within
my DBSCAN solution or come up with a new and more advanced approach.
Definitely, let me know your thoughts and if you have any ideas for
improvements. Happy to guide and collaborate! :)
The Object Detection is therefore for sure the biggest bottleneck within my
project right now because the Ground Extraction and the Tracking are just
performing well.

Moreover, make sure you star my repo so you get informed by future changes
;)

2018-08-23 11:07 GMT+08:00 Mrils <notifications@github.com>:
