### ISSUE TITLE
sensor_processing package miss key image copy operation

### ISSUE THREAD

**Issue by zhanghm1995** [appinho/ROS_Perception_Package_Kitti_Dataset#11]
Hi, your project is very awesome, and I am very inspired by this project. 
I found the `processImage` function in sensor_processing package don't work well as show as below:
```
cv::Mat sem_edge_img, sem_dil_img, sem_output;
	if(params_.sem_ed){
		cv::Canny(sem_image_, sem_edge_img, params_.sem_ed_min,
			params_.sem_ed_max, params_.sem_ed_kernel);
		cv::dilate(sem_edge_img, sem_dil_img, cv::Mat(), 
			cv::Point(-1, -1), 1, 1, 1);
		sem_image_.copyTo(sem_output, sem_dil_img);
	}

	// Publish
	cv_bridge::CvImage cv_semantic_image;
	cv_semantic_image.image = sem_output;
```
when the `if(params_.sem_ed)` condition is not true, the sem_output is null image, I think your should add `sem_output = sem_image_` above `cv_bridge::CvImage cv_semantic_image;`.
Thanks!

**Comment by appinho** [comment]
Thank you Andrew for your kind words! I definitely appreciate this!

And even a bigger thanks for pointing out this flaw :) well spotted!! I’m
gonna make a PR within the next days and make the change you suggested!

Because I love the field of perception of self driving cars and the people
that are working on it as well, I am curious to ask where your from and
what kind of research you pursue? Always interested in this!

And if you have some more ideas or suggestions, please point them out! I
love open source and that’s why I shared my work! Also make sure to give my
repo a star ⭐️ to push it further to top :)
Thanks!

Happy hacking,
Simon

**Comment by zhanghm1995** [comment]
Thank you for your reply. 

I am a postgraduate student in Beijing Institute of Technology, China.And I am also love the environment perception of autonomous vehicle. 

My researh fields maily about DATMO (detection and tracking moving objects) by using sensors fusion techniques, mainly using lidar and camera.
I found your work is very similar with mine, and it's very glad for me to communicate with you. Hope we can keep contact with each other.

**Comment by appinho** [comment]
No problem!

That’s exactly my expertise as well! What is your GitHub name so I can see
your projects as well :) ?

**Comment by zhanghm1995** [comment]
It's [https://github.com/zhanghming ](https://github.com/zhanghming).
And my frequently used email is zhanghm_1995@qq.com, you can send email to this address.

Thanks a lot!

**Comment by appinho** [comment]
Done!
