### ISSUE TITLE
Did anyone try running ukf without world coordinate?

### ISSUE THREAD

**Issue by Mrils** [appinho/ROS_Perception_Package_Kitti_Dataset#8]
Hello! I've tried to modify your code to suit my project —— tracking vehicles on highway.
    It works but there are also some issues ： I cannot get the conversion from vehicle coordinate system to world coordinate system so that I only run code on vehicle coordinate system， and the bounding box, the velocity and yaw of vehicle also seem strange.
    Did you try running ukf without world coordinate?And any advise?
    Thanks a lot!

**Comment by appinho** [comment]
First, @Mrils awesome work that you applied my repo to motorway scenarios! Would be great if you can share some visual results!

Second, you can try to track objects in relative coordinates however you will face relative velocities, that can be negative if the ego vehicle is faster than the object vehicle, and dependent orientations since you can loose straight driving object vehicles only if the ego vehicle makes a lane change (unless should be minor for motorway situations).

Would be great if you can explain me why the transformation to world coordinates didn’t work for you!

**Comment by appinho** [comment]
Any other issues or feedback @mrils ?
